# Generated by Django 5.2.4 on 2025-07-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactDetails",
            fields=[
                ("ID", models.BigAutoField(primary_key=True, serialize=False)),
                ("FirstName", models.CharField(max_length=200)),
                ("LastName", models.CharField(max_length=200)),
                ("Address", models.CharField(max_length=200)),
                ("Email", models.EmailField(max_length=200, unique=True)),
                ("PhoneNumber", models.IntegerField(max_length=12)),
            ],
        ),
    ]
