# Generated by Django 5.2.4 on 2025-07-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactdetails",
            name="Address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="contactdetails",
            name="PhoneNumber",
            field=models.IntegerField(max_length=10),
        ),
    ]
