# Generated by Django 5.2.4 on 2025-07-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contactdetails",
            unique_together={("FirstName", "LastName")},
        ),
    ]
