# Generated by Django 5.2.4 on 2025-07-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contactdetails_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactdetails",
            name="Address",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="contactdetails",
            name="PhoneNumber",
            field=models.CharField(max_length=10),
        ),
    ]
